apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smnetwork-frontend-deployment
spec:
  selector:
    matchLabels: 
      app: smnetwork
  replicas: 1
  template:
    metadata:
      labels:
        app: smnetwork
    spec:
      containers:
      - name: frontend
        image: schmidtp0740/smnetwork_frontend:${WERCKER_GIT_BRANCH}-${WERCKER_GIT_COMMIT}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000