apiVersion: v1
kind: Service
metadata:
  name: smnetwork-service
spec:
  type: LoadBalancer
  ports:
  - name: backend-port
    port: 8080
    targetPort: 8080
  - name: frontend-port
    port: 80
    targetPort: 5000
  selector:
    app: smnetwork